name: test

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.16.x', '1.17.x']
        platform: [ubuntu-latest]

    name: test
    runs-on: ${{ matrix.platform }}
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: install golanci-linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1

      - name: run unit tests
        run: make test

      - name: run linter
        run: make lint

      - name: upload code coverage
        uses: codecov/codecov-action@v2.0.2
        if: contains(github.ref, 'master')
        with:
          file: ./cover.out
